# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'to-do' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for to-do

pod 'RealmSwift'
pod 'SwipeCellKit'
pod 'ChameleonFramework/Swift', :git => 'https://github.com/wowansm/Chameleon.git', :branch => 'swift5'

end
